### ISSUE TITLE
Bug? `tool.poetry.packages[0]` must not contain {'to'} properties

### ISSUE THREAD

**Issue by jamesbraza** [abravalheri/validate-pyproject#177]
From https://python-poetry.org/docs/pyproject/#packages:

> The `to` parameter is designed to specify the relative destination path where the package will be located upon installation. This allows for greater control over the organization of packages within your project’s structure.

However, when I have a `to` in my `pyproject.toml`'s `packages` like this:

```toml
[tool.poetry]
packages = [
    {from = "app", include = "apples", to = "foo/app"},
    {include = "app/*.py", to = "foo"},
    {include = "app/py.typed", to = "foo"},
]
```

With `validate-pyproject` v0.18 I get:

```none
Invalid file: pyproject.toml
[ERROR] `tool.poetry.packages[0]` must not contain {'to'} properties
```

Is this a bug in `validate-pyproject`? And if not, why is `to` disallowed?

**Comment by abravalheri** [comment]
I believe in this case, the definitions are coming from https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/partial-poetry.json .

It might be worth it to double-check if that spec makes sense (sorry, I have not used poetry many times).

**Comment by henryiii** [comment]
The is fairly new: https://python-poetry.org/history/#180---2024-02-25 and needs to be updated in SchemaStore. Contributions usually welcome (also can open an issue there).

**Comment by jamesbraza** [comment]
Made https://github.com/SchemaStore/schemastore/pull/3807 to match https://github.com/python-poetry/poetry-core/pull/672, closing this out

**Comment by henryiii** [comment]
Synced: https://github.com/henryiii/validate-pyproject-schema-store/releases/tag/2024.05.24
