### ISSUE TITLE
Please install `tomli` (TOML parser)

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [abravalheri/validate-pyproject#186]
Although `validate-pyproject` is documented to support Python ≥ 3.8, it fails to run on Python 3.10 after a `pipx` installation.

```console
$ pipx install validate-pyproject
  installed package validate-pyproject 0.18, installed using Python 3.10.12
  These apps are now globally available
    - validate-pyproject
done! ✨ 🌟 ✨
$ 
$ validate-pyproject --help
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/validate-pyproject/lib/python3.10/site-packages/validate_pyproject/_tomllib.py", line 7, in <module>
    from tomli import TOMLDecodeError, loads
ModuleNotFoundError: No module named 'tomli'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/validate-pyproject/lib/python3.10/site-packages/validate_pyproject/_tomllib.py", line 10, in <module>
    from toml import TomlDecodeError as TOMLDecodeError  # type: ignore
ModuleNotFoundError: No module named 'toml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/bin/validate-pyproject", line 5, in <module>
    from validate_pyproject.cli import main
  File "/home/user/.local/pipx/venvs/validate-pyproject/lib/python3.10/site-packages/validate_pyproject/cli.py", line 30, in <module>
    from . import _tomllib as tomllib
  File "/home/user/.local/pipx/venvs/validate-pyproject/lib/python3.10/site-packages/validate_pyproject/_tomllib.py", line 13, in <module>
    raise ImportError("Please install `tomli` (TOML parser)") from ex
ImportError: Please install `tomli` (TOML parser)
$ 
```
While the `tomli` dependency is documented, it does not seem to be taken into account by `pipx`:
https://github.com/abravalheri/validate-pyproject/blob/e1aa94607ce086991e6b37b09cae3dfb3c623c8a/setup.cfg#L65-L69

**Comment by DimitriPapadopoulos** [comment]
This works of course:
```
pipx install validate-pyproject[all]
```
The `tomli` library should not be an **optional** dependency under `extra_requires` for Python < 3.11.

**Comment by abravalheri** [comment]
> The tomli library should not be an optional dependency under extra_requires for Python < 3.11.

Hi @DimitriPapadopoulos, please read the rationale in the README. It is unlikely this is going to change.

As a library, having `tomli` as optional dependency is completely fine. For CLI usage, the installation instructions are well documented.

**Comment by DimitriPapadopoulos** [comment]
Which exact part of the README? I can understand you want to "_keep the dependencies minimal_", but it doesn't really make sense to make `tomli` optional when the purpose of the library is to validate a TOML file.

**Comment by DimitriPapadopoulos** [comment]
My wrong, I wasn't aware that the library itself consumes a dict, not a TOML file. The issue arises from distributing the library and the command in a single Python package, although they have conflicting needs in terms of dependencies (the library must remain as lightweight as possible while the command requires additional packages to merely run).

Anyway, the problem will go away as distributions start shipping Python ≥ 3.11.

**Comment by DimitriPapadopoulos** [comment]
Would you at least agree on a PR that changes the CLI to catch the `ModuleNotFoundError` and print and nicer error message?
