### ISSUE TITLE
Rename testing extra to test?

### ISSUE THREAD

**Issue by henryiii** [abravalheri/validate-pyproject#209]
Currently the test extra is named `testing`, instead of `test`, which is the name reserved for use as a testing extra (see https://packaging.python.org/en/latest/specifications/core-metadata/#provides-extra-multiple-use). Future tools like hatch might start detecting this automatically.

**Comment by abravalheri** [comment]
I agree this is something worth changing.

When I first added it, I had a look around and I remembered seeing some PyPA tools using `testing`. But now there seems to be a consensus around `test` and these tools have since move on to `test`.
