### ISSUE TITLE
[BUG] Urlspec dependency with environment markers within pyproject.toml dependencies section is reported as pep508 offending rule

### ISSUE THREAD

**Issue by dre-hh** [abravalheri/validate-pyproject#214]
An urlspec like this 
torch @ https://download.pytorch.org/whl/cpu/torch-2.3.1%2Bcpu-cp311-cp311-linux_x86_64.whl; platform_system == 'Linux' and platform_machine == 'x86_64'

is causing a validation error when used inside a pyrpoject.toml dependecies section.

I have submited a detailed description to 
 https://github.com/pypa/setuptools/issues/4690, but it might be the reason is in validate-pyproject.
 
 Using validate-pyproject 0.21 with setuptools 75.2.0 on Mac OS Arm64 Sonoma. Same behaviour on Ubuntu 22.04 x86_64

**Comment by abravalheri** [comment]
Please see the explanation in https://github.com/pypa/setuptools/issues/4690.
