### ISSUE TITLE
[ERROR] SchemaWithDuplicatedId: All schemas used in the validator MUST define a unique toplevel `"$id"`

### ISSUE THREAD

**Issue by pquentin** [abravalheri/validate-pyproject#30]
When I run `validate-pyproject` with version 0.6.1 install with `[all]` with Python 3.8.13, I get exit code 1 and the following output:

```
[WARNING] validate_pyproject.api.load_builtin_plugin overwrites `tool.distutils` schema
[ERROR] SchemaWithDuplicatedId: All schemas used in the validator MUST define a unique toplevel `"$id"`.
`$id = 'https://docs.python.org/3/install/'` was found at least twice.
```

This also happens in directories without a `pyproject.toml` file, which is why I did not include mine. What does that mean?

**Comment by abravalheri** [comment]
Hi @pquentin thank you very much for reporting this. Do you have a small script to reproduce the problem?

I am trying:
```bash
% mkdir /tmp/_test
% cd /tmp/_test
% echo "" | pipx run 'validate-pyproject[all]==0.6.1'
Valid file
```

**Comment by pquentin** [comment]
It's very weird. I'm using Python 3.8.13 on Fedora, where I can reproduce with a clean venv. But the same operations in Docker just work:

```
FROM python:3.8.13

RUN python3.8 -m venv test
RUN test/bin/pip install validate-pyproject[all]
RUN test/bin/pip list
RUN test/bin/pip --version
RUN test/bin/python --version
RUN echo '' > pyproject.toml
RUN test/bin/validate-pyproject pyproject.toml
```

**Comment by abravalheri** [comment]
Do you know if there is any fedora-based Python container that can be used for testing instead of Debian?

**Comment by pquentin** [comment]
I tried with Python 3.8, but that works too. Sorry, I don't have any ideas left and I won't take the time to debug. Closing for now.
