### ISSUE TITLE
pre_compile fails when installed using setuptools instead of PEP517

### ISSUE THREAD

**Issue by bnavigator** [abravalheri/validate-pyproject#52]
When using the legacy setuptools `python setup.py` from the PyPI published sdist, setuptools installs a `validate_pyproject-*.egg-info` (also pre-packaged in the sdist),  ~~or `validate_pyproject-0.9.dist-info` (`setup.py bdist_wheel`)~~*. This clashes with `pre_compile.load_licenses()` which looks for the hard-coded dist_name `validate-pyproject`. Note the difference in `-` vs `_`.

https://github.com/abravalheri/validate-pyproject/blob/d87a6028122df4598e42d2f6516d3653ff90e818/src/validate_pyproject/pre_compile/__init__.py#L116

https://github.com/abravalheri/validate-pyproject/blob/d87a6028122df4598e42d2f6516d3653ff90e818/src/validate_pyproject/__init__.py#L11

Workaround: Use a PEP517 installer like `pip` or `build`+`install`.

\* Edit: `validate_pyproject-0.9.dist-info` is also the one installed with a PEP517 frontend and found fine by `importlib.metadata.files('validate-pyproject')`

**Comment by abravalheri** [comment]
Thank you very much @bnavigator for reporting this problem.

Just a quick question, if I change to `dist_name = "validate_pyproject"`, will it solve the problem?

**Comment by bnavigator** [comment]
https://docs.python.org/3/library/importlib.metadata.html#distribution-versions and https://setuptools.pypa.io/en/latest/deprecated/python_eggs.html#sources-txt-source-files-manifest seem to contradict each other here.

In line with #50 it might be worth not to rely on `importlib.metadata.files()` at all.

**Comment by bnavigator** [comment]
Update: With importlib_metadata 4.11.4 overriding the importlib.metadata from Python 3.10.5, the filelist changes, but ist still wrong:

```
abuild@skylab:~> python3
Python 3.10.5 (main, Jun 06 2022, 22:34:44) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata as _M
>>> from pprint import pprint
>>> pprint(_M.files("validate_pyproject"))
[PackagePath('LICENSE.txt'),
 PackagePath('README.rst'),
 PackagePath('pyproject.toml'),
 PackagePath('setup.cfg'),
 PackagePath('setup.py'),
 PackagePath('src/validate_pyproject/__init__.py'),
 PackagePath('src/validate_pyproject/__main__.py'),
 PackagePath('src/validate_pyproject/api.py'),
 PackagePath('src/validate_pyproject/cli.py'),
 PackagePath('src/validate_pyproject/error_reporting.py'),
 PackagePath('src/validate_pyproject/errors.py'),
 PackagePath('src/validate_pyproject/extra_validations.py'),
 PackagePath('src/validate_pyproject/formats.py'),
 PackagePath('src/validate_pyproject/types.py'),
 PackagePath('src/validate_pyproject.egg-info/PKG-INFO'),
 PackagePath('src/validate_pyproject.egg-info/SOURCES.txt'),
 PackagePath('src/validate_pyproject.egg-info/dependency_links.txt'),
 PackagePath('src/validate_pyproject.egg-info/entry_points.txt'),
 PackagePath('src/validate_pyproject.egg-info/not-zip-safe'),
 PackagePath('src/validate_pyproject.egg-info/requires.txt'),
 PackagePath('src/validate_pyproject.egg-info/top_level.txt'),
 PackagePath('src/validate_pyproject/_vendor/__init__.py'),
 PackagePath('src/validate_pyproject/_vendor/fastjsonschema/__init__.py'),
 PackagePath('src/validate_pyproject/_vendor/fastjsonschema/__main__.py'),
 PackagePath('src/validate_pyproject/_vendor/fastjsonschema/draft04.py'),
 PackagePath('src/validate_pyproject/_vendor/fastjsonschema/draft06.py'),
 PackagePath('src/validate_pyproject/_vendor/fastjsonschema/draft07.py'),
 PackagePath('src/validate_pyproject/_vendor/fastjsonschema/exceptions.py'),
 PackagePath('src/validate_pyproject/_vendor/fastjsonschema/generator.py'),
 PackagePath('src/validate_pyproject/_vendor/fastjsonschema/indent.py'),
 PackagePath('src/validate_pyproject/_vendor/fastjsonschema/ref_resolver.py'),
 PackagePath('src/validate_pyproject/_vendor/fastjsonschema/version.py'),
 PackagePath('src/validate_pyproject/plugins/__init__.py'),
 PackagePath('src/validate_pyproject/pre_compile/__init__.py'),
 PackagePath('src/validate_pyproject/pre_compile/__main__.py'),
 PackagePath('src/validate_pyproject/pre_compile/cli.py'),
 PackagePath('src/validate_pyproject/vendoring/__init__.py'),
 PackagePath('src/validate_pyproject/vendoring/__main__.py'),
 PackagePath('src/validate_pyproject/vendoring/cli.py')]
>>> 

```

**Comment by jaraco** [comment]
Ideally, Setuptools would not generate egg-info, and would instead generate dist-info with a RECORD. If it did that, then `importlib.metadata.files` would provide a consistent experience. The fallback to `SOURCES.txt` for egg-info is there to give its best effort at the list of files in the project, but as you can see, it's inconsistent.

**Comment by abravalheri** [comment]
@bnavigator what is the motivation behind using the deprecated `python setup.py install`? (I am imagining that you are using `install`...).

It should be possible to support this use case, however there will be an increase in complexity and maintenance effort, which I would like to avoid...

It non trivial to satisfy these constraints simultaneously: a) my desire to avoid double bookkeeping b) (potential) lack of symlinks on Windows c) Legacy installation methods like `python setup.py`.

**Comment by bnavigator** [comment]
No motivation at all. It's the legacy way of packaging and so far the default when generating recipes for a rpm build. I switched to PEP517 and made the error go away.

The easiest way to avoid future errors like this is to remote the setup.py completely and force your users to use PEP517.

**Comment by abravalheri** [comment]
> The easiest way to avoid future errors like this is to remove the setup.py completely and force your users to use PEP517.

Thank you very much for the information @bnavigator. I think I will follow this direction.
