### ISSUE TITLE
Support PEP 639

### ISSUE THREAD

**Issue by iudeen** [abravalheri/validate-pyproject#70]
As per latest PEP0639 deprecates subkeys in license - https://peps.python.org/pep-0639/#deprecate-license-key-table-subkeys

This causes the following error in projects that adopted the new standard. (Especially the ones that adopted Hatch)

```
$ validate-pyproject pyproject.toml                          
Invalid file: pyproject.toml
[ERROR] `project.license` must be valid exactly by one definition (2 matches found):

    - keys:
        'file': {type: string}
      required: ['file']
    - keys:
        'text': {type: string}
      required: ['text']
```
As per PEP document: 
> Table values for the license key in the [project] table, including the text and file table subkeys, are now deprecated. If the new license-files key is present, build tools MUST raise an error if the license key is defined and has a value other than a single top-level string.

**Comment by abravalheri** [comment]
Hi @iudeen thank you very much for reporting this.

The status of PEP 639 is still Draft, so the new format is still not a standard.

**Comment by iudeen** [comment]
Hey! Thanks, yes I just went through the discord discussions. Seems like it's delayed because of a Moon launch 😅

**Comment by henryiii** [comment]
This is provisionally accepted, so it's time to implement, I think. It would be great if we could also do validation on the license specifiers. Maybe even have a strict mode that validates that they are already normalized (maybe combined with #179?)
