### ISSUE TITLE
Report likely mistakes as warnings

### ISSUE THREAD

**Issue by cmarqu** [abravalheri/validate-pyproject#76]
My `pyproject.toml` contained an entry in `authors` that was technically not an error, but it would have been nice to get a warning about:
```
[project]
name = "bad-authors"
version = "0.1.0"
authors = [
    {author = "Foo Bar", email = "foo.bar@example.com"}
]
```
(`author` should have been `name`).

This is not an error since only one of `name` and `email` are required as per 
https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#authors-maintainers, but maybe it could be a warning if an unknown "extra" key has been found.

**Comment by abravalheri** [comment]
Hi @cmarqu , I disagree that using an extra undefined key is technically correct. The specification is clear about that:

> ... accept an array of tables with 2 keys: `name` and `email`.

This specification does not leave any margin for other undefined keys.

**Comment by cmarqu** [comment]
Okay, so it is a plain bug in validate-pyproject then?

**Comment by abravalheri** [comment]
Yes, we need to fix that :)
