### ISSUE TITLE
vendoring of fastjsonschema

### ISSUE THREAD

**Issue by tijuca** [abravalheri/validate-pyproject#77]
Hi,

as pdm-pep517 has or will finally morphing into [pdm-backend](https://github.com/pdm-project/pdm-backend) it uses a vendored version of `validate-pyproject`.

Currently I'm trying to package pdm-backend for Debian and if possible we try to avoid vendored stuff as it's hard to maintain from a security perspective. Now even `validate-pyproject` uses also a vendored package [fastjsonschema](https://github.com/horejsek/python-fastjsonschema).

It's possible to use vendoring in Debian as long all is DFSG compliance, but .... :smiling_face_with_tear: 
What are the reasons for vendoring `fastjsonschema` in `validate-pyproject`? So far I analyzed the version used in `validate-pyproject `is based on the not recent version the project of `fastjsonschema` has moved to. Isn't it possible to drop the vendoring and depend on the native package?

I've tried to get the tests adjusted to use a system based version of `fastjsonschema` but failed. Using non vendored package would make the life of distro packagers more easy.

Thanks!

**Comment by abravalheri** [comment]
Hi @tijuca thanks for reaching out.

I believe it should be possible to do it. I just haven't had the time to take a look yet 😅 and fix eventual inconsistencies. Sorry for that.

Initially, I took the decision to vendor the dependency because I needed a quick fix for some problems in fastjsonschema. But since then the fixes were merged.

**Comment by tijuca** [comment]
Thanks for your quick feedback!

I totally understand why sometimes vendoring is needed to make progress. Thanks for considering to drop it in one of the next next releases.

Locally I was now able to patch the source so the tests will use a local installed version of fastjsonschema (the most recent version). Some tests I needed to disable as they are depending on the folder structure used in the folder `_vendor` while set up replacements. Tough these tests are useful, they probaly (just) need some rewrite so they use non related vendored data.
