### ISSUE TITLE
CLI hangs when no arguments provided

### ISSUE THREAD

**Issue by layday** [abravalheri/validate-pyproject#94]
Perhaps foolishly, I expected `validate-pyproject` to auto-detect my `pyproject.toml` inside the current working directory; but `pipx run validate-pyproject[all]` hangs indefinitely, presumably waiting for stdin (line 219 of `cli.py`).

**Comment by abravalheri** [comment]
Hi @layday, thank you very much for pointing that out.

Probably it should make clear to the user that it is going to use the stdin.
